### ISSUE TITLE
Change Demo Link in README.md

### ISSUE THREAD

**Issue by frederickjh** [higuma/web-audio-recorder-js#26]
The current demo link in README.md ([https://higuma.github.io/web-audio-recorder-js/](https://higuma.github.io/web-audio-recorder-js/)) returns an error when selecting an audio device as in [#16].

Change the link to one that works like the one given in https://github.com/higuma/web-audio-recorder-js/issues/2#issuecomment-198204165 ([https://boo-higuma.ssl-lolipop.jp/gh-pages/web-audio-recorder-js/](https://boo-higuma.ssl-lolipop.jp/gh-pages/web-audio-recorder-js/)).

**Comment by makc** [comment]
indeed gh-pages link works, but it does not mute audio when recording, resulting in feedback loop

**Comment by x5engine** [comment]
even this link 

https://boo-higuma.ssl-lolipop.jp/gh-pages/web-audio-recorder-js/

does not record anything

**Comment by ericmulder1980** [comment]
The new lolipop.jp link works fine in Firefox / Safari / Chrome on OSX but you need to manually set the microphone input level. If you have issues with recording at least provide some information about the context of your test. Which OS, which browser, etc.

**Comment by x5engine** [comment]
@ericmulder1980 normal setup as everyone!
Chrome latest version!!!

**Comment by frederickjh** [comment]
Fixed in the last two commits.
