### ISSUE TITLE
convert to mp3 mono

### ISSUE THREAD

**Issue by javismiles** [higuma/web-audio-recorder-js#3]
good day, i read this
"If you use MP3 encoding, you cannot change .numChannels from default (current MP3 encoder supports 2-channel stereo only)."

in my case i need to convert microphone input to Mono Mp3, how could i change the code to allow for that?
thank you so much

**Comment by higuma** [comment]
Hi Javier,
Sorry for late for answer.

MP3 encoder uses LAME MP3 library. As original LAME is written in C, I have made a JavaScript library for web browsers using C-to-JavaScript converter.

<https://github.com/higuma/mp3-lame-encoder-js>

LAME is mostly made for Hi-Fi audio. It is not difficult to setup LAME for 2-ch stereo. But It needs special configuration for mono. In fact (to tell you honestly), I do not know how to configure to mono correctly (I tried but could not). Please see the following issue.

<https://github.com/higuma/mp3-lame-encoder-js/issues/1>

Numbers of people have tried to make LAME JavaScript encoder with mono. I have checked some of them a few month ago (from May to July). But I found none of them was successful.

If you can use another encoding than MP3, Ogg Vorbis is easier. You can set numChannels to 1.

**Comment by javismiles** [comment]
Dear Higuma, thank you for your reply , i have to say i have found a few people using Lame to export Mono MP3 with no problems, i will post the links here soon, so i dont think that's a problem really

**Comment by javismiles** [comment]
here you have it 
https://github.com/zhuker/lamejs
can export to mono 1 channel and it works well

**Comment by javismiles** [comment]
Blixt also exports with lame to mono 1 channel 
https://github.com/blixt/js-lameworker

**Comment by javismiles** [comment]
so those two libraries above use Lame to export to 1 channel mono successfully,
would be awesome if you could add it to yours as well this capability yeah

**Comment by higuma** [comment]
Thank you for your nice imformation. I will check them later.
Anyway, using these libraries is probabry better for you.
I want to improve my library also, but not now...

**Comment by javismiles** [comment]
in many ways your library is better and more complete than the others,
but the others have 1 or 2 things that are missing in yours, ideal world
would be mixture of both :))
best my friend
:)

Javier ideami
Ideami Studios
San Francisco / Barcelona
+1 408 634 9071
http://torchprinciple.com
http://ideami.com
http://posterini.com
http://incredivid.com
<http://torchprinciple.com>

**Comment by higuma** [comment]
Thank you Javier.
I apologize that I closed this issue.
I really want to improve my library. But I have no time for it now.
(Hence my reply is alwayes late, but your responce is always very quick)
When I find time and manage to make improvement, I let you know.

Best regards,
Yuji

2015-10-15 21:17 GMT+09:00 Javier <notifications@github.com>:

**Comment by javismiles** [comment]
thank you Yuji,
your monitoring feedback issue may be related to this
https://github.com/mattdiamond/Recorderjs/issues/45


Javier ideami
Ideami Studios
San Francisco / Barcelona
+1 408 634 9071
http://torchprinciple.com
http://ideami.com
http://posterini.com
http://incredivid.com
<http://torchprinciple.com>
