### ISSUE TITLE
npm package

### ISSUE THREAD

**Issue by hmontazeri** [higuma/web-audio-recorder-js#39]
Hi @higuma,

Any reason why it’s not published to npm? 

Best,
Hamed

**Comment by hmontazeri** [comment]
Never mind found the other issue in this

**Comment by tiggem1993** [comment]
> Never mind found the other issue in this

Hi @hmontazeri , I am also looking some solution to integrate this library in my ReactJs web app project as like other NPM package.  Did you get any solution? Please share with us. https://github.com/higuma/web-audio-recorder-js/issues/44
