### ISSUE TITLE
How to import WebAudioRecorder.js in ReactJs component?

### ISSUE THREAD

**Issue by tiggem1993** [higuma/web-audio-recorder-js#44]
My ReactJs project is based on [ReactJs Boilerplate](https://github.com/react-boilerplate/react-boilerplate) project architecture. I have a ReactJs Component in which I have to record audio in ogg format.  I have seen three similar node modules links for same library which is also bit confusing for us to choose right one. 

**QUESTION 1**: Please let us know which one is working perfect for ReactJs project:

1. [web-audio-recorder-js-webpack](https://www.npmjs.com/package/web-audio-recorder-js-webpack) 
2. [web-audio-recorder-js](https://www.npmjs.com/package/web-audio-recorder-js)
3. [web-audio-recorder-fixed](https://www.npmjs.com/package/web-audio-recorder-fixed)

**QUESTION 2**: How to import in my ReactJS component?
As I was expecting from node libraries are mostly used without calling in html. I mean without using the script tag. But you have mention to call in HTML. Which is logically incorrect with ReactJs, Vue and Angular . So I would like to request you to please suggest us how to use it with this kind of framework projects.

`<script src="javascripts/WebAudioRecorder.js"></script>`

**Comment by crobinson42** [comment]
This is an implementation/learning/knowledge question relating nothing to this library.

Post your question on Stackoverflow.com.

@tiggem1993 close this issue.
