### ISSUE TITLE
How can I check the length in seconds of the recorded audio file?

### ISSUE THREAD

**Issue by DamianoP** [higuma/web-audio-recorder-js#45]
I would like to ignore audio clips that are less than a second long, how can this be done ? I was thinking of using blob.size, but I don't understand how it relates to the length of the sound

**Comment by DamianoP** [comment]
For example, the "timelimit" parameter allows you to set a maximum limit to the recording duration.
I would like to find out how to set a minimum limit to the recording duration.

**Comment by bart-stevens** [comment]
A bit late ... but perhaps someone still can use this
I don't know if this is the cleanest way, but it is possible to add a variable TotalTime.
(I used the minified version WebAudioRecorder.min.js, I added in the code below the surrounding code, so only the specific parts with TotalTime are new)

in the beginning initialize it with 0:
   this.input=this.context.createGain();i.connect(this.input);this.buffer=[];this.TotalTime=0;
and at the end of the recording:
   finishRecording:function(){if(this.isRecording()){this.TotalTime=(Date.now()-this.startTime)*0.001;this.input.disconnect();

**Comment by bart-stevens** [comment]
in the non minified version (WebAudioRecorder.js):
line 58 and next:
    this.input = this.context.createGain();
    sourceNode.connect(this.input);
    this.buffer = [];
    this.TotalTime=0;
...

line 125 and next ones:
      if (this.isRecording()) {
        this.TotalTime=(Date.now()-this.startTime)*0.001;
        this.input.disconnect();
...
