### ISSUE TITLE
Can i record more thant 10 min

### ISSUE THREAD

**Issue by haroldgarcia23** [higuma/web-audio-recorder-js#5]
I need a plugin to record max 1 hr

**Comment by higuma** [comment]
10 minutes is just a demo limitation (only for safety guard).
There is no limitation for the library itself (you can set longer time as possible).

To change max time on demo, please switch branch to gh-pages and check for index.html source,
and find the following line.

```
<input id="time-limit" type="range" min="1" max="10" value="3">
```

You can change max (in minutes) to appropriate value you need.
But it may consume much memory (please take care with your responsibility).

Also, you should always select "Encode on recording background" for this purpose. "Encode after recording (safer)" accumulates uncompressed buffers during recording. It uses much bigger memory than "Encode on recording background".

**Comment by haroldgarcia23** [comment]
Thanks 

Also how i can disable the audio out put when recording. Is Creating alot of feed back.

Thanks
