### ISSUE TITLE
Storing files to server

### ISSUE THREAD

**Issue by ahmadkhudeish** [higuma/web-audio-recorder-js#7]
Hi there,

Really nice plugin. I was just wondering would I be able to store the file to the server using PHP with this plugin?

Thanks

**Comment by higuma** [comment]
Hi, thank you for your comment.

I don't know anything about PHP (I use Ruby or node.js on server side). I think this can help you. This example sends form data.

<https://gist.github.com/ebidel/2410898>

As for this library, data is obtained by Blob object. You can send it directly by `xhr.send(blob)` (you don't have to save to file). See the following.

<https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest#send()>
